trigger:
 - main

pool:
   vmImage: 'ubuntu-latest' 

variables:
   imageName: 'pipelines-javascript-docker'

steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: 'container1'
     command: 'build'
     Dockerfile: 'app/Dockerfile'